### ISSUE TITLE
Add participant ID to protocol

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#181]
It may be helpful to add an optional participant ID field to protocols and to be included in data. Maybe also providing the option to set the S3 folder field equal to this in Remote Data Store.

**Comment by MatthewGerber** [comment]
If the participant ID resides in the protocol file, you will need to create a different protocol for each participant. Is this really what you mean?

If you want to attach a participant ID to each datum object, it seems like that's already taken care of with the Datum.DeviceId field.

If you want to attach a participant-supplied ID (e.g., their assigned ID within the study) to each datum object rather than the arbitrary device ID, then just create a start-up script that prompts for this. The script response will contain both the device ID and the participant-supplied ID, allowing you to link all data to the participant ID.

As for the S3 folder name containing a user ID, this probably isn't the most useful thing to do since all of our data analysis and visualization are done outside of S3. Sorting on user ID is easy once the data are in Tableau, R, or SQL.

Are you thinking of something beyond the cases above?

**Comment by wesbonelli** [comment]
> If the participant ID resides in the protocol file, you will need to create a different protocol for each participant. Is this really what you mean?

This is actually what we've done for the studies thus far. Participants were identified by a four-digit ID specified by the researchers, and each participant had their own folder named after their ID.

> If you want to attach a participant-supplied ID (e.g., their assigned ID within the study) to each datum object rather than the arbitrary device ID, then just create a start-up script that prompts for this. The script response will contain both the device ID and the participant-supplied ID, allowing you to link all data to the participant ID.

This makes a lot of sense. The only objection I can anticipate would be that it might cause issues if participants incorrectly entered their ID, but they could be asked to do that in the initial lab session w/ oversight from an RA. That covers everything I know of; I think you're right, it doesn't seem necessary.

**Comment by MatthewGerber** [comment]
Early in the development of Sensus I wrestled with the problem of linking data with participants. Right now this link requires manual intervention, either by the study designer (like when you embedded IDs in the S3 folder names) or by the user (by prompting users for their IDs). Because these are manual procedures, they will never be completely error free. Ideally, I think we'd have a web-based tool that accepts a list of participants with contact information, assigns each an arbitrary identifier, and sends out protocols to participants with embedded identifiers (this is what you have been doing manually). The system would retain the mapping from individuals to identifiers in a secure way...typical anonymization for such studies.

Does this make sense? Can you put it in the design for the portal?

**Comment by wesbonelli** [comment]
Yes, definitely. This sounds like it would solve multiple issues at once. When we asked the psych researchers for feedback regarding Sensus, one of their main points was that it would be nice to be able to create and distribute protocols all from a computer. Maybe we could build protocol creation into the system so everything could be handled from the portal.

**Comment by MatthewGerber** [comment]
A web-based protocol creator would be nice, but it will be a significant challenge due to the complexity of the JSON within a protocol. Xamarin supports the creation of .NET and Mac apps, too. If we added one of those to the Sensus solution in Xamarin Studio we might be able to hook into the app codebase, which would provide access to the serialization routines that generate the protocol files. I'm going to close this issue and create others for this stuff.
