### ISSUE TITLE
iOS scripts will not fire if the app has not entered the foreground since a prior script fired

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#223]
v9.8.1
iOS issue but I think it's benign to Android and worth adding to both platforms.

On iOS, if multiple times or windows are scheduled for a script, and the first script notification is not responded to and the app is not brought into the foreground, none of the following scripts will fire. Scripts are currently scheduled using only 1 callback at a time, with each callback scheduled after the prior one runs. I've tried out scheduling all callbacks for a single day when the protocol starts (scheduling all for the duration of the study may be an option too) and it seems to solve the problem without unexpected behavior. @MatthewGerber, what are your thoughts on this?

**Comment by MatthewGerber** [comment]
Interesting idea. How will you handle the case where a few notifications
pile up and then the user opens the app? Will they fill out all surveys or
just one survey?

**Comment by wesbonelli** [comment]
Right now it opens the script corresponding to the first notification and that one only. I think this is ok and actually desirable if the notifications are all from the same script, but if not I think we'd want the user to have the chance to answer one copy of each different script definition. For example in our studies, if there's a random time script notification and then an end of day script notification, we want both responses, not just the random time one. I'm working on getting it to behave this way.

**Comment by MatthewGerber** [comment]
This sounds reasonable. It also intersects what I'm doing with scripts in
the script-tray branch. The basic idea of this branch is that we're going
to have a holding place for all scripts that have fired. The user will be
able to view all pending scripts and complete them as desired.

On Aug 11, 2016 2:54 PM, "Wes Bonelli" <notifications@github.com> wrote:

Right now it opens the script corresponding to the first notification and
that one only. I think this is ok and actually desirable if the
notifications are all from the same script, but if not I think we'd want
the user to have the chance to answer one copy of each different script
definition. For example in our studies, if there's a random time script
notification and then an end of day script notification, we want both
responses, not just the random time one. I'm working on getting it to
behave this way.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/predictive-technology-laboratory/sensus/issues/223#issuecomment-239256371>,
or mute the thread

**Comment by MatthewGerber** [comment]
Just to be clear I think we still need to use your changes that schedule
all notifications for the day and fire a particular script upon app open.
You could add your commits to the script-tray branch when it gets closer to
merge. Feel free to take a look now at what I'm doing.

**Comment by wesbonelli** [comment]
Ok, great; sorry for closing and reopening last night. I was trying out a Github client app on my phone and didn't mean to.

**Comment by MatthewGerber** [comment]
Fixed with earlier work.
