### ISSUE TITLE
@Capstone - Would like the ability to add a weekly survey

### ISSUE THREAD

**Issue by brendobendo** [predictive-technology-laboratory/sensus#283]
Answer the following questions depending on the type of issue you are submitting.

# For All Issues
### Which version of Sensus are you currently using?
13.1.1

### Which operating system(s) does this issue involve (Android, iOS, or both)?
both

# For Enhancement Issues
### What would you like Sensus to do that it does not already do?
Would like the ability to issue surveys at larger time intervals than daily, such as every two days, three days, or even every week. This will be especially important for mobility surveys.

**Comment by MatthewGerber** [comment]
@wesbonelli Can you work on this one? I think it should be pretty straightforward. Below the "Random Windows:" field, add an integer input field named "Random Windows Interval (Days):" field with range [1,int.MaxValue] that defaults to 1. The value of this field indicates how many days to move forward when scheduling each sequence of random windows. For example, with random windows set to "9:00" and interval set to 1, the schedule would be 9am on day 1, 9am on day 2, etc. With interval set to 2, the schedule would be 9am on day 1, 9am on day 3, etc.

Feel free to suggest a better alternative.

**Comment by wesbonelli** [comment]
@MatthewGerber Sure. Your approach seems like the easiest. If this is time sensitive, I can just do that. @brendobendo, is there a deadline for this?

Alternatively, we could model the time trigger setup after the way `ScriptInput`s are done. Create a new `TimeTriggersPage` accessible from `ScriptRunnerPage` by a "Time Triggers" button. Adding a new trigger could open a dialog with options "Random Window" or "Specific Time", then take you to `TimeTriggerPage` with conditionally visible properties like on `ScriptInputPage`. From this page we could set any properties necessary, and I think the advantage to this is that it will make any new functionality easier to add and more organized (rather than continuing to grow `ScriptRunnerPage` with more options). Time triggers currently only implement interval scheduling at 1 day intervals, with greater intervals coming soon per this post topic, but we could add calendar scheduling too: i.e., trigger the script at time X or within window X-Y every Monday and Wednesday weekly, or on the 3rd and 15th of every month, for example.

**Comment by MatthewGerber** [comment]
@wesbonelli The proposed alternative is headed in a nice direction. It would be even better to unify the time triggers with the probe-based triggers. Have a single Triggers page that shows probe- and time-based triggers. @mrucker suggested this a while back. It's not going to be trivial, since the two trigger types have very different underlying implementations, but it might be worth it if done properly (for the reasons you suggest).

See what @brendobendo has in mind for a deadline and go from there.

**Comment by wesbonelli** [comment]
@MatthewGerber Ok, great. It seems like it would also make for a more logical user interface. Sounds good.

**Comment by brendobendo** [comment]
@wesbonelli I'd like to have our team test this feature before the next semester starts, so if you could have it done by the 9th or 10th, that'd be great.

**Comment by wesbonelli** [comment]
@brendobendo Ok, sure.

@MatthewGerber I've got few other things to work on over the break. I can take your first approach for now in order to make sure something is working by the 9th, then work on the other implementation as time permits?

**Comment by MatthewGerber** [comment]
Sounds good

**Comment by wesbonelli** [comment]
@MatthewGerber When scheduling callbacks more than 24 days in the future, the `delayMS` parameter passed into the shared and platform-specific `CallbackScheduler` classes overflows and schedules the callbacks in the past, causing them to trigger immediately. Switching to `delaySeconds` or `delayMinutes` both seemed reasonable but I wanted to check with you first.

**Comment by MatthewGerber** [comment]
Even better would be to change to `TimeSpan delay`.

**Comment by mrucker** [comment]
@wesbonelli, while you're working on this stuff, I'm on campus in my office
every day this week from 9-5.

I'll be doing my own research, but I'd be happy to talk through any code
you might get stuck on.

**Comment by wesbonelli** [comment]
@MatthewGerber Ok, will do.

@mrucker I'm not back in town til Friday so will have to reach out via email in the meantime, but thanks!

**Comment by wesbonelli** [comment]
@brendobendo I won't be able to keep working on the code for scheduling beyond 24 days until the 17th or 18th. The changes letting you schedule scripts at variable intervals are done, though; as long as you set the protocol length to 24 days or shorter it should work fine. I can send you download links you can use for testing if you give me your computing id. I'll need the UDID's of any iPhones you'll be testing on, you can get those by following the steps [here](http://whatsmyudid.com/).

When do you plan to start running your study?

**Comment by MatthewGerber** [comment]
Wes -

Can you PR the changes you have so far?

Matt

**Comment by wesbonelli** [comment]
@MatthewGerber I've just opened a PR into develop.

**Comment by MatthewGerber** [comment]
Resolved by #318. Will release via Diawi for internal testing.
