### ISSUE TITLE
Send push notifications

### ISSUE THREAD

**Issue by ckohout** [predictive-technology-laboratory/sensus#329]
### Which version of Sensus are you currently using?
any version
### Which operating system(s) does this issue involve (Android, iOS, or both)?
both
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
We need Sensus to be able to deliver a custom push notification.

**Comment by MatthewGerber** [comment]
@wesbonelli This is a pressing issue for one of Prof. Barnes's and my capstone projects. Do you have time to work on it?

**Comment by wesbonelli** [comment]
@MatthewGerber Yes, I can look at it today and this weekend. Should I prioritize this ahead of #193?

**Comment by MatthewGerber** [comment]
@wesbonelli Yes I think it's more important than #193 right now. You can investigate the overall push notification architectures for Android and iOS over the weekend, and we can talk Monday about our particular needs and implementation strategies early next week. Would you be available Monday to chat via Skype?

**Comment by wesbonelli** [comment]
@MatthewGerber Sure. I'm very flexible Monday and can plan to Skype anytime.

**Comment by MatthewGerber** [comment]
Note for future:  As part of addressing this issue, we should figure out how to disentangle callback success from the notification. Right now, if the app is killed in the background prior to the delivery of a callback notification, then opening the notification will have no effect because the app will start fresh and won't recognize the delivered notification (on iOS at least).
