### ISSUE TITLE
Add display conditions to survey questions

### ISSUE THREAD

**Issue by brendobendo** [predictive-technology-laboratory/sensus#335]
### Which version of Sensus are you currently using?
13.3.0

### Which operating system(s) does this issue involve (Android, iOS, or both)?
iOS for sure but probably android too. 

### Describe the bug or enhancement. 
I would like the ability to add display conditions to survey questions.

**Comment by MatthewGerber** [comment]
@brendobendo I believe we were going about this the wrong way when testing. By design, if you want to condition the display of an input on another input's value, then the latter must be in a previous input group. It's not possible to show/hide an input in a group based on the value of an input in that same group. Try creating another input group and see if it works. Reopen this issue if it doesn't.
