### ISSUE TITLE
Add email exchange meta-data probe via Google Drive

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#350]

**Comment by MatthewGerber** [comment]
Do not need to add to Sensus. Can do this periodically outside of Sensus if needed:

https://flowingdata.com/2014/05/07/downloading-your-email-metadata/

**Comment by MatthewGerber** [comment]
@cw9dd Can you please experiment with periodic downloads of email meta-data from an EC2 instance, perhaps something like the link above? We won't add this to Sensus, but it would be nice to periodically download participants' email metadata and dump it into S3 for analysis.

**Comment by cw9dd** [comment]
Sure, I'll take a look.

**Comment by cw9dd** [comment]
Script ready to pull metadata. Will need participants to 1) supply email address and password; 2) enable IMAP service; 3) switch on "allow less secure apps" in Gmail account settings.

Caveat: there's a limit on the volume of metadata that can be downloaded in one sitting; when exceeded returns timeout error.

**Comment by MatthewGerber** [comment]
Does the script take parameters for the date range to retrieve?

**Comment by cw9dd** [comment]
No, as in substituting the spelled-out dates in the IMAP expression with parameters (in a similar fashion to using $1 $2 in bash script) doesn't work. However, I think (and tried with success), a way around this is to name the entire IMAP criterion expression (e.g., since ddmmyy before ddmmyy) as a parameter and use the parameter name in the place of the criterion argument in an applicable function. Date parameters can be concatenated with other strings (e.g., since) based on IMAP syntax to build the criterion expression and then be passed to a new parameter.

**Comment by MatthewGerber** [comment]
Okay, however it works is fine. Just wanted to make sure that we can get a
specific date range.

**Comment by cw9dd** [comment]
Okay.
