### ISSUE TITLE
HealthKit Height (polling) doesn’t work 

### ISSUE THREAD

**Issue by ikiana** [predictive-technology-laboratory/sensus#565]

**Comment by rd3fa** [comment]
@MatthewGerber  I pulled down the latest code and the height prob still seems to display with "[no data]". The problem is that there is a check in the DataRateCalculator.cs that states if(datum!= null && datum.Timestamp >= _startTimeStamp.Value) which in most cases are going to be evaluate as false. The reason for this is because the datum.TimeStamp is going to be when the user entered the height data into their health app. in my case I had entered my height data on 12/17/2017, so the sample data will get set to be dropped. Do we want to take the latest reading from the health app instead? Once I entered a new height on today's date it seemed to function correctly. I believe All of the sampling data for the healthkit will behave this way.
