### ISSUE TITLE
Upload to remote on WiFi connection

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#587]
Similar to what we did with power connection.

**Comment by MatthewGerber** [comment]
@clmckinley This would be next.

**Comment by clmckinley** [comment]
@MatthewGerber It looks like the wlan information on iOS is done via polling instead of a listening.  Did you intend this to be an android only feature?  

Alternatively it looks like connectivity is part of Xamarin.Essentials https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android I could rework the probes to be shared instead of device specific, but I don't know about adding Xamarin.Essentials into the project.

**Comment by MatthewGerber** [comment]
On Wed, Jan 23, 2019 at 3:35 PM clmckinley <notifications@github.com> wrote:

> @MatthewGerber <https://github.com/MatthewGerber> It looks like the wlan
> information on iOS is done via polling instead of a listening. Did you
> intend this to be an android only feature?
>
If it is not possible to wake up the app from the background on WiFi
connection (wouldn't be surprising on iOS), then yes this would be Android
only.

> Alternatively it looks like connectivity is part of Xamarin.Essentials
> https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android
> I could rework the probes to be shared instead of device specific, but I
> don't know about adding Xamarin.Essentials into the project.
>
We might consider doing this in the future, but for now we'll keep them
separate.
