### ISSUE TITLE
No Network

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#87]
How will Sensus behave if there is no network at all (no cellular or WiFi)? What will the data stores do? What will probe do that require network (e.g., for voice recognition)? Does everything smooth out when the network is restored?

**Comment by MatthewGerber** [comment]
@trishalaneeraj Have you tested this?

**Comment by trishalaneeraj** [comment]
When there is no network, Sensus continues to run the Protocol without stopping. However, as expected, there is no data upload during this period. 
The Protocol Report uploaded just after network is restored, is a larger report than others since it includes the reports that could not be uploaded due to no network.
Everything does smooth out after network is restored in terms of data collection and storage, as verified by going through uploaded JSON files and observing timestamps.
