### ISSUE TITLE
Killing Sensus on Android

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#89]
What happens if the user kills (forcefully quits) Sensus on Android using the app manager? Does Sensus restart? Crash? Something else?

**Comment by Marcus-Rosti** [comment]
I've noticed that stopping Sensus from the application will never truly close it.  
* Sensus running.
* Close Sensus from the app
* <1 minute later the app will open again

However, closing Sensus from application manager will close the app without a crash and leave it closed.  I think that's because it does something along the lines of  ```kill -9 Sensus```. Whereas, closing from Sensus requires it to clean itself up, which it must not do

**Comment by trishalaneeraj** [comment]
Sensus simply closes but the protocol does not stop running. There is no crash or restart. However, Sensus does not show up as one of the ‘Running Apps’ in the App Manager. When Sensus is opened, the protocol is seen running. (As observed on Android Lollipop.)

**Comment by MatthewGerber** [comment]
Closing via task switcher wasn't being processed properly, leaving the service hanging around. Fixed.

https://github.com/predictive-technology-laboratory/sensus/commit/262b542c7b6df5b23da1d7f991435afbe3373029
